apiVersion: v1
kind: ConfigMap
metadata:
  name: ssm-service-config
  namespace: ssm
data:
  SPRING_PROFILES_ACTIVE: "production"
  SSM_DATASOURCE_URL: "jdbc:oracle:thin:@//oracle-svc.oracle.svc.cluster.local:1521/ssmsrv"
  SSM_REDIS_HOST: "redis-svc.redis.svc.cluster.local"
  SSM_REDIS_PORT: "6379"
  EUREKA_DEFAULT_ZONE: "http://eureka-server-svc.dragon.svc.cluster.local/eureka"
  VAULT_BASE_URL: "http://vault-service-svc.vault.svc.cluster.local:8014"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318/v1/traces"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318/v1/logs"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318/v1/metrics"
